owner: hds-solutions
repo: status.ConfirmameTuPresencia.RSVP
user-agent: "ConfirmameTuPresencia.RSVP Upptime Checker"

sites:
  - name: ConfirmameTuPresencia.RSVP
    url: https://confirmametupresencia.rsvp/up
    headers:
      - "User-Agent: ConfirmameTuPresencia.RSVP Upptime"
    maxResponseTime: 2000

assignees:
  - $OWNER

status-website:
  name: ConfirmameTuPresencia.RSVP Status
  cname: status.confirmametupresencia.rsvp
  logoUrl: https://hds-solutions.net/build/assets/favicon-Ddt1gdk2.ico
  theme: night
  introTitle: "Status page for **[ConfirmameTuPresencia.RSVP](https://confirmametupresencia.rsvp)**"
  navbar:
    - title: Home
      href: https://confirmametupresencia.rsvp
    - title: Status
      href: /

i18n:
  footer: "[HDS Solutions](https://hds-solutions.net) &copy; 2025 Todos los derechos reservados, powered by [Upptime](https://upptime.js.org)"
